# Generated by Django 5.2.4 on 2025-12-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='uploads\\%Y\\%m\\%d'),
        ),
    ]
