# Generated by Django 5.2.4 on 2025-12-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_descriptions',
            field=models.TextField(max_length=1000),
        ),
    ]
